// Copyright 2026, Jerome Shidel
// The Clear BSD License
// All rights reserved.

unit GloDat;

{$mode objfpc}{$H+}

{$I patches.pp}  // Various compiler directives to "fix" things.
{$I version.def} // Version information defines

interface

uses
  {$IFDEF USES_CWString} cwstring, {$ENDIF}
  {$IFDEF UNIX}
  cthreads,
  {$ENDIF}
  Classes, SysUtils,
  { you can add units after this }
  Version,            // Program version information, generated by version.sh
  PasExt, BinTree;    // A couple basic MPLA units.

type
  // Types of Sections in a LST file
  TSectionKind = (
    skNone,      // Simply copied files or is not broken into multiple files
    skInterrupt, skCMOS, skFarCall, skI2C, skMemory, skMSR, skPort,
    skStandard,  // All the same
    skGlossary,  // Just glued together
    skTable,     // Just glued together in an empty comment section
    skSMM,       // Just glued together in separate "other" sections
    skLink,      // Just glued together in LINK comment sections
    skFAQ        // Just glued together in FAQ comment sections
  );

const
  {$IFDEF Windows}
  // Default output path for the compiled list release
  DirSource : String = '..\..\source\';
  // Default output path for the compiled list release
  DirOutput : String = '..\..\TheList\';
  {$ELSE}
  // Default output path for the compiled list release
  DirSource : String = '../../source/';
  // Default output path for the compiled list release
  DirOutput : String = '../../TheList/';
  {$ENDIF}

  // When enabled, program will use older methods for a couple LST files for
  // better compatibility with older parsers.
  LegacyMode : boolean = False;

  // Maximum bytes allowed in LST file. use -1 for no restriction.
  MaxFileSize : integer = 360 * 1024;

  // Enable more strict verification for use with CI/CD
  CICD : boolean = false;

  // File extension for all source files
  SrcExt = '.txt';
  // Directory Mapping file
  MapFile = '_Mapping' + SrcExt;
  // LST Header Data file
  HeaderFile = '_Header' + SrcExt;
  // TheList Release version, fairly static.
  ReleaseFile = '_Release' + SrcExt;
  // Leading characters for all section breaks
  SectionLead = '--------';
  // Number of charcters in a section break
  SectionWidth = 45;
  // The Interrup.1st default source directory subpath, may be different.
  // see the _MapFile
  IntFirstDir : String = 'Interrupt First';
  // Dir with Miscellaneous files that are just copied
  MiscFileDir : String = 'Miscellaneous';

    // That pesky non-interrupt list interrupt file :-)
  FILE_1ST = 'INTERRUP.1ST';

  // Maximum Length of Link Section ID in the LINKS.LST
  MaxLinkID : integer = 19;

  // Default conversion information of Long File Names to DOS versions
  DOSNAMES : array of record
    Name,                  // Long file name of File or Group Path.
    DOS : String;          // DOS file name for output file.
    Kind : TSectionKind;   // Type of sections used by that file.
  end = (
    // Miscellaneous files
    (Name:'Advertisement'+SrcExt;      DOS:'_ADVERT.TXT';  Kind:skNone),
    (Name:'Interrupt Primer'+SrcExt;   DOS:'INTERRUP.PRI'; Kind:skNone),
    (Name:'Need Help'+SrcExt;          DOS:'NEEDHELP.TXT'; Kind:skNone),
    (Name:'Ralf Brown'+SrcExt;         DOS:'RBROWN.TXT';   Kind:skNone),
    (Name:'Read Me Now'+SrcExt;        DOS:'README.NOW';   Kind:skNone),
    // List Files
    (Name:'Frequently-Asked Questions';DOS:'FAQ.LST';      Kind:skFAQ),
    (Name:'Bibliography';              DOS:'BIBLIO.LST';   Kind:skNone),
    (Name:'Category';                  DOS:'CATEGORY.KEY'; Kind:skNone),
    (Name:'Cmos-Memory Map';           DOS:'CMOS.LST';     Kind:skCMOS),
    (Name:'Far Call Interface';        DOS:'FARCALL.LST';  Kind:skFarCall),
    (Name:'Glossary';                  DOS:'GLOSSARY.LST'; Kind:skGlossary),
    (Name:'I2C-Bus Devices';           DOS:'I2C.LST';      Kind:skI2C),
    (Name:'Interrupt First';           DOS:FILE_1ST;       Kind:skNone),
    (Name:'Interrupt List';            DOS:'INTERRUP.LST'; Kind:skInterrupt),
    (Name:'Links';                     DOS:'LINKS.LST';    Kind:skLink),
    (Name:'Memory Map';                DOS:'MEMORY.LST';   Kind:skMemory),
    (Name:'Model-Specific Registers';  DOS:'MSR.LST';      Kind:skMSR),
    (Name:'Overview';                  DOS:'OVERVIEW.LST'; Kind:skNone),
    (Name:'Ports List';                DOS:'PORTS.LST';    Kind:skPort),
    (Name:'Selected Tables';           DOS:'TABLES.LST';   Kind:skTable),
    (Name:'System-Management Mode';    DOS:'SMM.LST';      Kind:skSMM)
  );

  // Sections to include in the INTERRUP.1ST file
  INTERRUPT_1ST : TArrayOfString = (
    'Filelist',
    'Copyright',
    'Disclaimer',
    'Availability',
    'Abbreviations',
    'Credits',
    'Addresses',
    'Trademarks',
    'Quotes',
    'Contact Info'
  );

  // General order of sections for all LST files (excluding INTERRUP.1ST).
  SECTION_ORDER : TArrayOfString = (
    'Introduction',
    'Disclaimer',
    'Note',
    'Flags',
    'Categories',
    'Category Keys',
    'Titles',
    '*',
    'Bibliography',
    'Undone',
    'History',
    'Contributors',
    'Credits',
    'Contact Info',
    'Admin'
  );

  // Default file information for INTERRUP.1ST's FILELIST section.
  DOSINFO : array of record
    Name, Text : String;
  end = (
  (Name:FILE_1ST;       Text:'this file'),
  (Name:'INTERRUP.LST'; Text:'Interrupts'),
  (Name:'PORTS.LST';    Text:'listing of I/O Ports'),
  (Name:'INTERRUP.PRI'; Text:'a brief primer on interrupts'),
  (Name:'OVERVIEW.LST'; Text:'brief listing of major uses of each interrupt'),
  (Name:'BIBLIO.LST';	Text:'bibliography of information sources for the list'),
  (Name:'CMOS.LST';     Text:'a description of the CMOS RAM data bytes'),
  (Name:'FARCALL.LST';  Text:'APIs available through FAR CALLs'),
  (Name:'GLOSSARY.LST'; Text:'a glossary of terms, abbreviations, and acronyms'),
  (Name:'MEMORY.LST';   Text:'format of the BIOS data area and other memory regions'),
  (Name:'MSR.LST';      Text:'a listing of Model-Specific Registers'),
  (Name:'CATEGORY.KEY'; Text:'descriptions of divider-line category letters'),
  (Name:'TABLES.LST';   Text:'a list of selected tables'),
  (Name:'LINKS.LST';    Text:'a list of links to reference and sites in the docs'),
  (Name:'FAQ.LST';      Text:'a list of frequently asked questions'),
  (Name:'README.NOW';   Text:'a read me document')
  );

{ ---------------------------------------------------------------------------- }
// Global processing variables
var
  // LST file source base directory
  BaseDir    : String;
  // LST Output FileName
  OutName    : String;
  // Maximum LST file title width (+1)
  TitleWidth : integer;
  // Header for LST file
  Header     : String;
  // Text from _Header file when present
  HeaderData : RawByteString;
  // Release Build Date/Time
  BuildTime  : TDateTime;
  // LST file release time stamp
  LastChange : String;
  // Current List Type
  SectionKind : TSectionKind;

  // For LST file headers, probably not used
  ReleaseVersion : RawByteString;
  // Working output data for LST file
  WorkingData  : RawByteString;
  // For verification all section comment files were used.
  CommentFiles : TStringList;
  // For assembling the section file data
  SectionTree : TBinaryTree;
  // 80-chars, but well will just test it is at least 70
  HeaderBar : String;
  // For verification, table numbers are unique
  TableTree : TBinaryTree;
  // Table Letter Code
  TableCode : String;
  // Highest Table Number
  TableHigh : integer;
  // Number of tables in LST
  TableCount : integer;

  // total of all entries in all sections
  TotalEntries : integer;
  // total of all tables in all sections
  TotalTables  : integer;
  // total number of actual errors
  TotalErrors  : integer;
  // Number of non-errors that will be problems for parsers
  TotalProblems : integer;
  // Less Severe problems that should be fixed at some point
  TotalWarnings : integer;
  // Number of entries with duplicate IDs
  TotalDuplicates : integer;
  // File Info for the FILELIST Section
  FileInfo : TBinaryTree;

{ ---------------------------------------------------------------------------- }
const
  // Filename to write file list of problem files.
  IssueFileName   : String = '';
  // Tracks if the Issues file has been opened.
  IssueFileOpen   : boolean = false;

var
  // The current working Entry file name for Issues.
  LastFileName: String;
  // The Issues text file handle.
  IssueFileHandle : Text;

implementation


end.
